"""
Enumerado de mensajes del sistema
"""

lecturaExitosa= 1
lecturaFueraRango= 2
lecturaError = 3
actuadoresPrendidos= 4
encendidoGrupoError= 5
encendidoGrupoOk= 6
encendidoGrupoParcial= 7
actuadoresApagados= 8
apagadoGrupoError= 9
apagadoGrupoOk= 10
apagadoGrupoParcial= 11
noExisteGrupoActuadores= 12
noExisteFactor= 13
cambioEstadoSistemaOk= 14
factorCreadoOk= 15
sensorCreadoOk= 16
grupoActuadoresCreadoOk= 17
actuadorCreadoOk= 18
tipoPlacaCreadaOk= 19
tipoActuadorCreadoOk= 20
placaAuxiliarCreadaOk= 21
nivelSeveridadCreadoOk= 22
filaPerfilActivacionAgregadaOk= 23
actuadoresEnPosicion= 24
movimientoGrupoError= 25
movimientoGrupoOk= 26
movimientoGrupoParcial= 27
actuadorAvanceCreadoOk= 28
posicionActuadorAvanceOk= 29
sensorPosicionActuadorAvanceOk= 30
estadoSistemaNoEsManual= 31
estadoSistemaNoManualNiAutomatico= 32
estadoActualNoEsConfiguracion= 33
dispositivoEliminadoOk= 34
factorEliminadoOk= 35
grupoActuadoresEliminadoOk= 36
nivelSeveridadEliminadoOk= 37
filaPerfilActivacionEliminadoOk= 38
noSePuedeInstanciarPlacaControladora= 39
encendidoActuadorError= 40
apagadoActuadorError= 41
lecturaFueraUmbral= 42
expiroTiempoPosiciones= 43
noSePuedeInstanciarPadre= 44
falloSMS= 45
noSePuedeInstanciarPlacaAuxiliar= 46
dispositivoRecuperado= 47
noSeEncuentraSensor= 48